name: 🌌 Cosmic README Updater

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-cosmic-dashboard:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 📦 Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: 📊 Check API Rate Limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/rate_limit_check.py

      - name: 🐍 Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: 🌠 Run Cosmic Fact Generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/cosmic_fact.py

      - name: 💭 Run AI Quote Generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/quote.py

      - name: 🔋 Run Battery Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/battery.py

      - name: 🎯 Run Trajectory Analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/trajectory.py

      - name: 📈 Run Evolution Graph Generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/evolution.py

      - name: 🛸 Run Starship Build Log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/shiplog.py

      - name: 🤖 Run Model of the Week
        run: python scripts/model_week.py

      - name: 🔥 Run Active Thrusters
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/thrusters.py

      - name: 🌊 Run Velocity Waves
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/velocity_waves.py

      - name: 🧬 Run DNA Helix Generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/dna_helix.py

      - name: 📡 Run Signal Radar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/signal_radar.py

      - name: 🎯 Run Mission Success Monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/mission_success.py

      - name: ⚡ Run Lightning Commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/lightning_commits.py

      - name: 🧠 Run Neural Pathways
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/neural_pathways.py

      - name: 🌌 Run Parallax Stars Generator
        run: python scripts/parallax_stars.py

      - name: 🧲 Run Gravity Well Generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/gravity_well.py

      - name: 🪐 Run Orbital Mechanics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/orbital_mechanics.py

      - name: 💾 Commit and Push Changes
        run: |
          git config --local user.name "Cosmic-Bot 🌌"
          git config --local user.email "cosmic-bot@users.noreply.github.com"
          mkdir -p data
          git add README.md assets/ dist/ data/ || true
          git diff --staged --quiet || git commit -m "⭐ Update Cosmic Dashboard - $(date +'%Y-%m-%d %H:%M UTC')"
          git push || echo "Nothing to push"

      - name: 📢 Notify on Failure
        if: failure()
        run: |
          echo "::error::Cosmic Dashboard update failed!"
          echo "Check the workflow logs for details."

